### ISSUE TITLE
drivers working with windows 10 release 1903

### ISSUE THREAD

**Issue by wayp55** [Destroyer/pinnacle-pctv-dual-hybrid-pro-pcie-3010ix#1]
English
________
Hello, I have managed to run the card with clean installation of windows 10 (1903) and with the drivers of this website:
http://www.catalog.update.microsoft.com/Search.aspx?q=pinnacle

exactly these: 	Pinnacle Systems driver update for Pinnacle PCTV 3010iX Dual Analog + DVB-T 

and the latest version of TVCenter 6.4.9.1033 downloadable from here:
ftp://ftp.pctvsystems.com/TV/application/TVC6/PCTVSystems_TVCenter_Setup_6.4.9.1033.exe

I inform you if you can help.

**********************************************************************************************
Spanish
______________
Hola, yo he conseguido hacer funcionar la tarjeta con instalacion limpia de windows 10 (1903) y con los drivers de esta web:
http://www.catalog.update.microsoft.com/Search.aspx?q=pinnacle

exactamente estos: 	Pinnacle Systems driver update for Pinnacle PCTV 3010iX Dual Analog + DVB-T 

y la última version del TVCenter 6.4.9.1033  descargable de aqui:
ftp://ftp.pctvsystems.com/TV/application/TVC6/PCTVSystems_TVCenter_Setup_6.4.9.1033.exe

informo por si puede ayudar

**Comment by Destroyer** [comment]
Hi, I'm aware of the drivers that come with windows update. However I wasn't able to use them with windows media center. I used special version from https://forums.mydigitallife.net/ to get media center working on windows 10, but with the drivers coming from windows update i couldn't find any tv channels. With this driver it worked. I've updated the readme to this more clear.

With that said I am no longer using this TV card as DVB-T has been deprecated in czech republic and will be shutting down at the end of the year.
